########## ShardingSphere对seata客户端的配置解析，具体详见org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingSphereTransactionManager
# 是否启用seata. 默认为true
sharding.transaction.seata.at.enable=true
# 当前客户端的id
client.application.id=user-service
# 事务分组. 等价于 seata.tx-service-group
client.transaction.service.group=user-service-group
client {
  application.id=user-service
  tx-service-group=user-service-group
}

# 服务注册与发现配置
registry {
  type = "nacos"
  nacos {
    server-addr = "127.0.0.1:8848"
    application = "seata-server"
    group = "SEATA_GROUP"
    namespace = "local"
  }
}

# 配置中心
config {
  type = "nacos"
  nacos {
    server-addr = "127.0.0.1:8848"
    group = "SEATA_GROUP"
    namespace = "local"
    data-id = "seataServer.properties"
  }
}
